### ISSUE TITLE
No module named 'ntsecuritycon'

### ISSUE THREAD

**Issue by williamtu** [smadaminov/ovs-dpdk-meson-issues#44]
[4/285] Generating vswitch-idl.ovsidl with a custom command (wrapped by meson to set env, to capture output)
FAILED: vswitch-idl.ovsidl
"C:\Users\root\AppData\Roaming\Python\Python39\Scripts\meson" "--internal" "exe" "--unpickle" "C:\k8s-antrea-dpdk-win\ovs\build\meson-private
\meson_exe_python.exe_243253e123a81c258980f5ae6f7edf9399a313cc.dat"
while executing ['C:\\Python39\\python.exe', 'C:/k8s-antrea-dpdk-win/ovs/ovsdb/ovsdb-idlc.in', 'annotate', 'C:/k8s-antrea-dpdk-win/ovs/vswitc
hd/vswitch.ovsschema', 'C:/k8s-antrea-dpdk-win/ovs/lib/vswitch-idl.ann']
--- stderr ---
Traceback (most recent call last):
  File "C:\k8s-antrea-dpdk-win\ovs\ovsdb\ovsdb-idlc.in", line 10, in <module>
    import ovs.db.schema
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\db\schema.py", line 19, in <module>
    import ovs.db.types
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\db\types.py", line 18, in <module>
    import ovs.db.data
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\db\data.py", line 22, in <module>
    import ovs.jsonrpc
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\jsonrpc.py", line 21, in <module>
    import ovs.poller
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\poller.py", line 26, in <module>
    import ovs.winutils as winutils
  File "C:\k8s-antrea-dpdk-win\ovs\python\ovs\winutils.py", line 20, in <module>
    import ntsecuritycon
ModuleNotFoundError: No module named 'ntsecuritycon'

**Comment by smadaminov** [comment]
added to the readme
